mysite/accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('profile/<str:username>/', views.user_profile, name='profile'),
]

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('post.urls')),
    path('accounts/', include('accounts.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mysite/post/urls.py
from django.urls import path

from . import views

app_name = 'post'

urlpatterns = [
    path('', views.post_list, name='post_list'),
    path('post_create/', views.post_create, name='post_create'),
]

mysite/accounts/models.py
from django.contrib.auth.base_user import AbstractBaseUser, BaseUserManager
from django.contrib.auth.models import PermissionsMixin
from django.db import models
from django.utils import timezone
from django.utils.translation import gettext_lazy as _

# Create your models here.


class UserManager(BaseUserManager):

    use_in_migrations = True

    def _create_user(self, username, email, password, **extra_fields):

        if not username:
            raise ValueError('The given username must be set')

        if not email:
            raise ValueError('The given email must be set')

        user = self.model(username=self.model.normalize_username(
            username), email=self.normalize_email(email), **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_user(self, username, email=None, password=None, **extra_fields):
        extra_fields.setdefault('is_staff', False)
        extra_fields.setdefault('is_superuser', False)
        return self._create_user(username, email, password, **extra_fields)

    def create_superuser(self, username, email, password, **extra_fields):
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)

        if extra_fields.get('is_staff') is not True:
            raise ValueError('Superuser must have is_staff=True')

        if extra_fields.get('is_superuser') is not True:
            raise ValueError('Superuser must have is_superuser=True')

        return self._create_user(username, email, password, **extra_fields)


class User(AbstractBaseUser, PermissionsMixin):
    username = models.CharField(max_length=25, unique=True)
    email = models.EmailField(unique=True)
    icon = models.ImageField(blank=True, null=True)
    introduction = models.CharField(max_length=75, blank=True, null=True)
    followers = models.ManyToManyField('self', blank=True, symmetrical=False)
    is_staff = models.BooleanField(
        _('staff status'),
        default=False,
        help_text=_(
            'Designates whether the user can log into this admin site.'),
    )
    is_active = models.BooleanField(
        _('active'),
        default=True,
        help_text=_(
            'Designates whether this user should be treated as active. '
            'Unselect this instead of deleting accounts.'
        ),
    )
    date_joined = models.DateTimeField(default=timezone.now)
    objects = UserManager()
    EMAIL_FIELD = 'email'
    USERNAME_FIELD = 'username'
    REQUIRED_FIELDS = ['email']

    class Meta:
        verbose_name = _('user')
        verbose_name_plural = _('users')

mysite/post/models.py
from django.db import models

# Create your models here.


class Post(models.Model):
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.content

mysite/post/forms.py
from django import forms

from .models import Post


class PostCreateForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = (
            'content',
        )
        widgets = {
            'content': forms.Textarea(
                attrs={'rows': 10, 'cols': 30, 'placeholder': 'ここに入力'}
            ),
        }

mysite/accounts/views.py
from django.contrib.auth import get_user_model
from django.shortcuts import render


def user_profile(request, username):
    context = {
        'User': get_user_model().objects.get(username=username),
    }
    return render(request, 'accounts/user_profile.html', context)

mysite/post/views.py
from django.shortcuts import render, redirect
from .forms import PostCreateForm
from .models import Post

# Create your views here.


def post_list(request):
    context = {
        'post_list': Post.objects.all(),
    }
    return render(request, 'post/post_list.html', context)


def post_create(request):
    if request.method == "POST":
        form = PostCreateForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('post:post_list')
    else:
        form = PostCreateForm()
    return render(request, 'post/post_create.html', {'form': form})

mysite/templates/accounts/user_profile.html
{% extends "base.html" %}

{% load static %}
{% block link %}
<link rel="stylesheet" type="text/css" href="{% static 'accounts/user_profile.css' %}">
{% endblock %}
{% block content %}
<div id="profile_page">
    <div id="user_status">
        {% if User.icon %}
        <img src="{{ User.icon.url }}" class="user-icon">
        {% else %}
        <img src="{% static 'images/user_icon.png' %}" class="user-icon">
        {% endif %}
        <h2>{{ User.username }}</h2>
        <p class="followBtn">フォローする</p>
    </div>
    <div id="user_post">
        <p class="list-t">{{ User.username }}さんの投稿一覧</p>
    </div>
</div>
{% endblock %}

mysite/templates/base.html
<!DOCTYPE html>
<html>
    {% block link %}
    {% endblock %}

<head>
    <meta charset="utf-8">
    <title>Django SNS</title>
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
</head>

<body>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
    <nav class="navbar navbar-default">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#gnavi">
                <span class="sr-only">メニュー</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a href="#" class="navbar-brand">DjangoSNS</a>
        </div>
    
        <div id="gnavi" class="collapse navbar-collapse">
            <ul class="nav navbar-nav navbar-right">
                <li><a href="{% url 'accounts:profile' request.user.username %}">プロフィール</a></li>
            </ul>
        </div>
    </nav>
    
    {% block content %}
    <!-- ここにページ毎のコンテンツを記述 -->
    {% endblock %}
</body>

</html>

mysite/templates/post/post_list.html
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <title>投稿一覧</title>
</head>

<body>
    {% extends "base.html" %}

    {% block content %}
    <h2>投稿一覧</h2>
    {% for post in post_list %}
    <p>{{ post.content }}</p>
    {% endfor %}
    {% endblock %}
</body>

</html>